# Generated by Django 3.2.5 on 2022-10-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221031_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.FileField(default=1, upload_to='posts/images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postaudio',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postdocument',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
