# Generated by Django 3.2.5 on 2022-11-01 18:13

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221101_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(upload_to=posts.models.post_image_upload_handler),
        ),
    ]
